CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE "ConnectionUsers" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Email" text NOT NULL,
    "CPF" text,
    "Phone" text,
    "Type" integer,
    "BirthDate" timestamp with time zone,
    "ImagePath" text,
    "IdentityId" text,
    CONSTRAINT "PK_ConnectionUsers" PRIMARY KEY ("Id")
);

CREATE TABLE "Exercises" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(100) NOT NULL,
    "Description" character varying(500) NOT NULL,
    "ImagePath" text,
    "VideoPath" text,
    CONSTRAINT "PK_Exercises" PRIMARY KEY ("Id")
);

CREATE TABLE "Gyms" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(100) NOT NULL,
    "Code" text,
    "Address" character varying(200) NOT NULL,
    "PhoneNumber" character varying(15) NOT NULL,
    "Email" character varying(100) NOT NULL,
    "Website" character varying(100),
    "Description" character varying(500),
    "ImageUrl" character varying(200),
    CONSTRAINT "PK_Gyms" PRIMARY KEY ("Id")
);

CREATE TABLE "Sessions" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Day" integer NOT NULL,
    "Repetitions" integer NOT NULL,
    "Series" integer NOT NULL,
    "Breaks" double precision NOT NULL,
    "Time" double precision NOT NULL,
    "ExerciseId" integer NOT NULL,
    "UserId" integer,
    CONSTRAINT "PK_Sessions" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Sessions_ConnectionUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "ConnectionUsers" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_Sessions_Exercises_ExerciseId" FOREIGN KEY ("ExerciseId") REFERENCES "Exercises" ("Id") ON DELETE CASCADE
);

CREATE TABLE "UserExercises" (
    "UserId" integer NOT NULL,
    "ExerciseId" integer NOT NULL,
    "Id" integer NOT NULL,
    CONSTRAINT "PK_UserExercises" PRIMARY KEY ("UserId", "ExerciseId"),
    CONSTRAINT "FK_UserExercises_ConnectionUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "ConnectionUsers" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_UserExercises_Exercises_ExerciseId" FOREIGN KEY ("ExerciseId") REFERENCES "Exercises" ("Id") ON DELETE CASCADE
);

CREATE TABLE "GymUsers" (
    "GymId" integer NOT NULL,
    "UserId" integer NOT NULL,
    "Id" integer NOT NULL,
    CONSTRAINT "PK_GymUsers" PRIMARY KEY ("UserId", "GymId"),
    CONSTRAINT "FK_GymUsers_ConnectionUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "ConnectionUsers" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_GymUsers_Gyms_GymId" FOREIGN KEY ("GymId") REFERENCES "Gyms" ("Id") ON DELETE CASCADE
);

INSERT INTO "Exercises" ("Id", "Description", "ImagePath", "Name", "VideoPath")
VALUES (1, 'Descrição do exercício', 'images/exe2.png', 'Agachamento Terra', 'videos/execucao.mp4');
INSERT INTO "Exercises" ("Id", "Description", "ImagePath", "Name", "VideoPath")
VALUES (2, 'Descrição do exercício', 'images/exe.png', 'Rosca Concentrada', 'videos/execucao.mp4');
INSERT INTO "Exercises" ("Id", "Description", "ImagePath", "Name", "VideoPath")
VALUES (3, 'Descrição do exercício', 'images/exe3.png', 'Supino Reto', 'videos/execucao.mp4');
INSERT INTO "Exercises" ("Id", "Description", "ImagePath", "Name", "VideoPath")
VALUES (4, 'Descrição do exercício', 'images/exe4.png', 'Puxada Aberta', 'videos/execucao.mp4');
INSERT INTO "Exercises" ("Id", "Description", "ImagePath", "Name", "VideoPath")
VALUES (5, 'Descrição do exercício', 'images/exe5.png', 'Levantamento Terra', 'videos/execucao.mp4');

CREATE INDEX "IX_GymUsers_GymId" ON "GymUsers" ("GymId");

CREATE INDEX "IX_Sessions_ExerciseId" ON "Sessions" ("ExerciseId");

CREATE INDEX "IX_Sessions_UserId" ON "Sessions" ("UserId");

CREATE INDEX "IX_UserExercises_ExerciseId" ON "UserExercises" ("ExerciseId");

SELECT setval(
    pg_get_serial_sequence('"Exercises"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM "Exercises") + 1,
        nextval(pg_get_serial_sequence('"Exercises"', 'Id'))),
    false);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250502155026_Initial', '9.0.4');

COMMIT;

