CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE "AspNetRoles" (
    "Id" text NOT NULL,
    "Name" character varying(256),
    "NormalizedName" character varying(256),
    "ConcurrencyStamp" text,
    CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
);

CREATE TABLE "Exercise" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text,
    "Description" text,
    "ImagePath" text,
    "VideoPath" text,
    CONSTRAINT "PK_Exercise" PRIMARY KEY ("Id")
);

CREATE TABLE "Gym" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text,
    "Code" text,
    "Address" text,
    "PhoneNumber" text,
    "Email" text,
    "Website" text,
    "Description" text,
    "ImageUrl" text,
    CONSTRAINT "PK_Gym" PRIMARY KEY ("Id")
);

CREATE TABLE "Users" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Email" text NOT NULL,
    "CPF" text,
    "Phone" text,
    "Type" integer,
    "BirthDate" timestamp with time zone,
    "ImagePath" text,
    "IdentityId" text,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
);

CREATE TABLE "AspNetRoleClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "RoleId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUsers" (
    "Id" text NOT NULL,
    "UserId" integer,
    "UserName" character varying(256),
    "NormalizedUserName" character varying(256),
    "Email" character varying(256),
    "NormalizedEmail" character varying(256),
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text,
    "SecurityStamp" text,
    "ConcurrencyStamp" text,
    "PhoneNumber" text,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL,
    CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetUsers_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id")
);

CREATE TABLE "GymUser" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "GymId" integer,
    "UserId" integer,
    CONSTRAINT "PK_GymUser" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_GymUser_Gym_GymId" FOREIGN KEY ("GymId") REFERENCES "Gym" ("Id"),
    CONSTRAINT "FK_GymUser_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id")
);

CREATE TABLE "Session" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Day" integer NOT NULL,
    "Repetitions" integer NOT NULL,
    "Series" integer NOT NULL,
    "Breaks" double precision NOT NULL,
    "Time" double precision NOT NULL,
    "ExerciseId" integer NOT NULL,
    "UserId" integer,
    CONSTRAINT "PK_Session" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Session_Exercise_ExerciseId" FOREIGN KEY ("ExerciseId") REFERENCES "Exercise" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Session_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id")
);

CREATE TABLE "UserExercise" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer,
    "ExerciseId" integer,
    CONSTRAINT "PK_UserExercise" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_UserExercise_Exercise_ExerciseId" FOREIGN KEY ("ExerciseId") REFERENCES "Exercise" ("Id"),
    CONSTRAINT "FK_UserExercise_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id")
);

CREATE TABLE "AspNetUserClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserLogins" (
    "LoginProvider" text NOT NULL,
    "ProviderKey" text NOT NULL,
    "ProviderDisplayName" text,
    "UserId" text NOT NULL,
    CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
    CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserRoles" (
    "UserId" text NOT NULL,
    "RoleId" text NOT NULL,
    CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
    CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserTokens" (
    "UserId" text NOT NULL,
    "LoginProvider" text NOT NULL,
    "Name" text NOT NULL,
    "Value" text,
    CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
    CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims" ("RoleId");

CREATE UNIQUE INDEX "RoleNameIndex" ON "AspNetRoles" ("NormalizedName");

CREATE INDEX "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims" ("UserId");

CREATE INDEX "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins" ("UserId");

CREATE INDEX "IX_AspNetUserRoles_RoleId" ON "AspNetUserRoles" ("RoleId");

CREATE INDEX "EmailIndex" ON "AspNetUsers" ("NormalizedEmail");

CREATE UNIQUE INDEX "IX_AspNetUsers_UserId" ON "AspNetUsers" ("UserId");

CREATE UNIQUE INDEX "UserNameIndex" ON "AspNetUsers" ("NormalizedUserName");

CREATE INDEX "IX_GymUser_GymId" ON "GymUser" ("GymId");

CREATE INDEX "IX_GymUser_UserId" ON "GymUser" ("UserId");

CREATE INDEX "IX_Session_ExerciseId" ON "Session" ("ExerciseId");

CREATE INDEX "IX_Session_UserId" ON "Session" ("UserId");

CREATE INDEX "IX_UserExercise_ExerciseId" ON "UserExercise" ("ExerciseId");

CREATE INDEX "IX_UserExercise_UserId" ON "UserExercise" ("UserId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250502154945_Initial', '9.0.4');

COMMIT;

