CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE "Exercises" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(100) NOT NULL,
    "Description" character varying(500) NOT NULL,
    "ImagePath" text,
    "VideoPath" text,
    CONSTRAINT "PK_Exercises" PRIMARY KEY ("Id")
);

CREATE TABLE "Gyms" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(100) NOT NULL,
    "Address" character varying(200) NOT NULL,
    "PhoneNumber" character varying(15) NOT NULL,
    "Email" character varying(100) NOT NULL,
    "Website" character varying(100),
    "Description" character varying(500),
    "ImageUrl" character varying(200),
    CONSTRAINT "PK_Gyms" PRIMARY KEY ("Id")
);

CREATE TABLE "Users" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "CPF" text,
    "Name" character varying(100) NOT NULL,
    "Email" character varying(100) NOT NULL,
    "Phone" text,
    "Type" text,
    "BirthDate" timestamp with time zone,
    "ImagePath" text,
    "Password" text NOT NULL,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
);

CREATE TABLE "GymUsers" (
    "GymId" integer NOT NULL,
    "UserId" integer NOT NULL,
    "Id" integer NOT NULL,
    CONSTRAINT "PK_GymUsers" PRIMARY KEY ("UserId", "GymId"),
    CONSTRAINT "FK_GymUsers_Gyms_GymId" FOREIGN KEY ("GymId") REFERENCES "Gyms" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_GymUsers_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Sessions" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Repetitions" integer NOT NULL,
    "Series" integer NOT NULL,
    "Breaks" double precision NOT NULL,
    "Time" double precision NOT NULL,
    "ExerciseId" integer NOT NULL,
    "UserId" integer,
    CONSTRAINT "PK_Sessions" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Sessions_Exercises_ExerciseId" FOREIGN KEY ("ExerciseId") REFERENCES "Exercises" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Sessions_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE SET NULL
);

CREATE TABLE "UserExercises" (
    "UserId" integer NOT NULL,
    "ExerciseId" integer NOT NULL,
    "Id" integer NOT NULL,
    CONSTRAINT "PK_UserExercises" PRIMARY KEY ("UserId", "ExerciseId"),
    CONSTRAINT "FK_UserExercises_Exercises_ExerciseId" FOREIGN KEY ("ExerciseId") REFERENCES "Exercises" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_UserExercises_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

INSERT INTO "Exercises" ("Id", "Description", "ImagePath", "Name", "VideoPath")
VALUES (1, 'Descrição do exercício', 'images/exe2.png', 'Agachamento Terra', 'videos/execucao.mp4');
INSERT INTO "Exercises" ("Id", "Description", "ImagePath", "Name", "VideoPath")
VALUES (2, 'Descrição do exercício', 'images/exe.png', 'Rosca Concentrada', 'videos/execucao.mp4');
INSERT INTO "Exercises" ("Id", "Description", "ImagePath", "Name", "VideoPath")
VALUES (3, 'Descrição do exercício', 'images/exe3.png', 'Supino Reto', 'videos/execucao.mp4');
INSERT INTO "Exercises" ("Id", "Description", "ImagePath", "Name", "VideoPath")
VALUES (4, 'Descrição do exercício', 'images/exe4.png', 'Puxada Aberta', 'videos/execucao.mp4');
INSERT INTO "Exercises" ("Id", "Description", "ImagePath", "Name", "VideoPath")
VALUES (5, 'Descrição do exercício', 'images/exe5.png', 'Levantamento Terra', 'videos/execucao.mp4');

INSERT INTO "Users" ("Id", "BirthDate", "CPF", "Email", "ImagePath", "Name", "Password", "Phone", "Type")
VALUES (1, NULL, '123.456.789-01', 'adm@gmail.com', 'defaultphoto.jpg', 'Admin', 'AQAAAAIAAYagAAAAEITz1a/77vT3ZwjAw9XZcxFPRitGSXwDvuJjK7glqQRx/GPpsO6EJKFIzKIVTagQEw==', NULL, 'Administrador');
INSERT INTO "Users" ("Id", "BirthDate", "CPF", "Email", "ImagePath", "Name", "Password", "Phone", "Type")
VALUES (2, NULL, '987.654.321-09', 'jose@gmail.com', 'defaultphoto.jpg', 'José', 'AQAAAAIAAYagAAAAEJOl9fQBaXVQKbgJSzw2uZYjkaF4qJpGTXPCQMo9KPV7A7JML+fMw1aibI9Svg/RZA==', NULL, 'Professor');
INSERT INTO "Users" ("Id", "BirthDate", "CPF", "Email", "ImagePath", "Name", "Password", "Phone", "Type")
VALUES (3, NULL, '111.222.333-44', 'maria@gmail.com', 'defaultphoto.jpg', 'Maria', 'AQAAAAIAAYagAAAAEJIH5ovAp/VkhDS5IuJgynsgaiJAOFEDk9A23AH/7iijxtdGkHQ7fU9FqXfF2vsF8w==', NULL, 'Aluno');
INSERT INTO "Users" ("Id", "BirthDate", "CPF", "Email", "ImagePath", "Name", "Password", "Phone", "Type")
VALUES (4, NULL, '555.666.777-88', 'joao@gmail.com', 'defaultphoto.jpg', 'João', 'AQAAAAIAAYagAAAAENW9ZFQMqhhtQKS4aCaGV6BxST8OrPzmTN06NsrGjf5xc01Uv0AJLVkR6YAjIxmuxw==', NULL, 'Aluno');

CREATE INDEX "IX_GymUsers_GymId" ON "GymUsers" ("GymId");

CREATE INDEX "IX_Sessions_ExerciseId" ON "Sessions" ("ExerciseId");

CREATE INDEX "IX_Sessions_UserId" ON "Sessions" ("UserId");

CREATE INDEX "IX_UserExercises_ExerciseId" ON "UserExercises" ("ExerciseId");

SELECT setval(
    pg_get_serial_sequence('"Exercises"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM "Exercises") + 1,
        nextval(pg_get_serial_sequence('"Exercises"', 'Id'))),
    false);
SELECT setval(
    pg_get_serial_sequence('"Users"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM "Users") + 1,
        nextval(pg_get_serial_sequence('"Users"', 'Id'))),
    false);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250408195029_InitialDb', '9.0.4');

COMMIT;

