### Teste de Login com credenciais válidas
POST http://localhost:5217/api/auth/login
Content-Type: application/json

{
  "email": "adm@gmail.com",
  "password": "password"
}

### Teste de Login com credenciais inválidas
POST http://localhost:5217/api/auth/login
Content-Type: application/json

{
  "email": "adm@gmail.com",
  "password": "wrongpassword"
}

### Teste de Login com usuário inexistente
POST http://localhost:5217/api/auth/login
Content-Type: application/json

{
  "email": "nonexistentuser@gmail.com",
  "password": "password"
}
